### ISSUE TITLE
LiDAR-only odometry is failed with M2DGR dataset

### ISSUE THREAD

**Issue by Taeyoung96** [hku-mars/LiDAR_IMU_Init#19]
@zfc-zfc   
Thanks for your great work.  
When I use LiDAR-IMU init with my custom data, LiDAR-only odometry is failed.  

I use the [M2DGR dataset](https://github.com/SJTU-ViSYS/M2DGR) (Velodnye VLP-32 and handsfree IMU)

My custom m2dgr yaml file is like below.  
```
common:
    lid_topic:  "/velodyne_points"
    imu_topic:  "/handsfree/imu"

preprocess:
    lidar_type: 2                # Velodyne LiDAR
    scan_line: 32
    blind: 2
    feature_extract_en: true

initialization:
    cut_frame: true # false: do not cut input pointcloud
    cut_frame_num: 3 # must be positive integer
    orig_odom_freq: 10
    mean_acc_norm: 9.81 # 1: for livox built-in IMU
    online_refine_time: 15.0
    data_accum_length: 200
    Rot_LI_cov: [ 0.00005, 0.00005, 0.00005 ]
    Trans_LI_cov: [ 0.0001, 0.0001, 0.0001 ]

mapping:
    filter_size_surf: 0.5
    filter_size_map: 0.5
    gyr_cov: 10
    acc_cov: 2
    b_acc_cov: 0.0001
    b_gyr_cov: 0.0001
    det_range: 200.0

publish:
    path_en:  true
    scan_publish_en:  false       # false: close all the point cloud output
    dense_publish_en: false       # false: low down the points number in a global-frame point clouds scan.
    scan_bodyframe_pub_en: true  # true: output the point cloud scans in IMU-body-frame

pcd_save:
    pcd_save_en: false
    interval: -1                 # how many LiDAR frames saved in each pcd file; 
                                 # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.
```

And the result looks like this, I used the `door_02` sequence. (outdoor scene) 
![Screenshot from 2022-08-19 17-09-52](https://user-images.githubusercontent.com/41863759/185574404-c2315ae1-cb70-4e9e-b5a2-324c0e6e52d2.png)

LiDAR-only odometry is failed so online refinement is inaccurate.  

Can you tell me what caused this?  
Do I need to modify the config file?
I saw this issue #11 , is it impossible to calculate lidar-only odometry measured by Ground robot?

I'd appreciate it if you give me an answer.  
Thanks,
